Firstly, we import the libraries required for this question

In [1]:
import numpy as np 
import math
import matplotlib.pyplot as plt


We will be using the power method to approximate the largest eigenvalue and its associated eigenvector of the matrix

<center> $ M = \begin{bmatrix} 
  -2 & 1 & 0 & 0
\\ 1 & -2 & 1 & 0
\\ 0 & 1 & -2 & 1
\\ 0 & 0 & 1 & -2
\end{bmatrix} 
y^{(0)} = 
\begin{bmatrix} 
   1
\\ 0
\\ 0 
\\ 0 
\end{bmatrix} $

We define the Matrix

In [2]:
A = np.array([[-2, 1, 0, 0], 
              [1, -2, 1, 0],
              [0, 1, -2, 1],
              [0, 0, 1, -2]])

First choose a starting vector y0

In [10]:
x = np.array([[1,0,0,0]]).T

Define the tolerance for the approximated eigenvalue and the eigen vector to ensure accuracy between exact and approximated solution.

In [53]:
tol = 1e-36

Next, we define the maximum number of iterations 

In [54]:
maxit = 100

Define a variable to store previous approximations

In [55]:
prev = 0

Initiallize loop to iterate using the power method to approximate the largest eigenvector and eigenvalue.

The formula we use is the following :

$$x_{i+1} = \frac{Ax_{i}}{|Ax_{i}|}$$

Where:
- $|Ax_{i}|$ : Euclidean norm of vector $Ax_{i}$

Then, we also calculate the approximated largest eigenvalue of the matrix by applying the equation:

$$λ_{i}= \frac{x_{i}^{T} Ax_{i}}{x_{i}^{T}x_{i}} $$

The convergence of the largest eigenvector and eigenvalue will be checked by using the difference between the current approximation and the previous value. We iterate until it reaches the tolerance value or when it reaches the maximum iteration.


In [58]:
#initiate iteration
for i in range(maxit):
    # Calculate approximated eigenvector
    x = A@x / np.linalg.norm(A@x)
  
    # # Calculate approximated eigenvalue
    eig = ( x.T@A@x ) / ( x.T@x )
  
    # Check reaults using tolerance
    if np.abs( eig-prev ) < tol:
        break
  
    # Store current value
    prev = eig
  

#print
print(float(eig))
print(x)

-3.618033988749895
[[-0.37174804]
 [ 0.60150096]
 [-0.60150095]
 [ 0.37174803]]


We calculate the exact eigenvalue and eigenvector

In [59]:
np.linalg.eig(A) # to approximate exact eigenvalue and eigenvector

(array([-3.61803399, -2.61803399, -0.38196601, -1.38196601]),
 array([[ 0.37174803,  0.60150096, -0.37174803, -0.60150096],
        [-0.60150096, -0.37174803, -0.60150096, -0.37174803],
        [ 0.60150096, -0.37174803, -0.60150096,  0.37174803],
        [-0.37174803,  0.60150096, -0.37174803,  0.60150096]]))